### ISSUE TITLE
Add new plugin in craclord

### ISSUE THREAD

**Issue by ytronics** [jmmcatee/cracklord#104]
Hello,

I wrote a simple plugin and I am trying to add it to Cracklord-system. 
However I have problem with adding my plugin. I cannot see the supported algorithms in "Select hash type" tab. See the pictures:
![decrypt](https://cloud.githubusercontent.com/assets/16799278/12979368/44011478-d0df-11e5-9eb1-bb1d53c2fe76.png)
![new_job](https://cloud.githubusercontent.com/assets/16799278/12979379/4de7d7a6-d0df-11e5-8ec6-03704c11e0ad.png)

I created my decrypt.go file based on hashcat.go file. 
The supported hash algorithms for my plugin are:
var supportedHash = map[string]string{
	"descrypt, DES(Unix), Traditional DES": "1500",
    "WPA/WPA2":                             "2500",
}

var supportedHashInt = map[string]int{
	"descrypt, DES(Unix), Traditional DES": 1500,
	"WPA/WPA2":                             2500,
}

I also had updated all .conf files

I added and applied all necessary changes in Cracklord for my plugin, but I cannot see its functionality. 

Could you explain me an approach for adding new plugins in Cracklord?

Thanks in advance!

Best regards

**Comment by jmmcatee** [comment]
Did you get this working?

**Comment by ytronics** [comment]
Yes, I fixed my errors and I am developing my tool.

**Comment by jmmcatee** [comment]
Awesome. Feel free to ask any questions you have along the way.
