### ISSUE TITLE
Getting the remaining time from console output

### ISSUE THREAD

**Issue by ytronics** [jmmcatee/cracklord#107]
Hello,

I want to get the remaining time from a console output generated by my tool. 
An example of the generated output is: | .................... | Time elapsed: 4.0m | Time remaining: ~5.9m | Freq: 175.00MHz | ..........

Could you suggest me how I can get _"Time remaining: ~5.9m |" _ and add it to job-progress-chart?

In my tasker file I am defined following:
Regular expression is: 
regTimeRemaining,  err = regexp.Compile(`\.\.\.\.\.\.\.\.\.\.\.\.\.\| Time remaining:.*\((.*?)\)`)
I am not sure in the correctness of the regular expression.  

etcMatch := regTimeRemaining.FindStringSubmatch(status)
		log.WithField("etcMatch", etcMatch).Debug("Matching Remaining time of completion.")

		if len(etcMatch) == 30 {
			v.job.ETC = etcMatch[10]
		}else {
  			v.job.ETC = "Not Available"
    		}

I use the structure of hashcat tool for reference. Therefore my tool is based on it. However I cannot attach algorithm's remaining time to progress doughnut 

Thanks in advance!
Best regards,
Yanko

**Comment by jmmcatee** [comment]
Right now you are checking if the length of the string array is 30, which it will not be. You should check if the etchMatch (a string array) is length of 1, which means you found one match. If that is true then you can add the value the ETC.

**Comment by ytronics** [comment]
Hello,

Yes, you are right. 
But I have problems by parsing the console output. When I run my tool, it prints following in the console:
| Time elapsed: 7.8m | Time remaining: ~2.0d | Freq: 175.00MHz | Temp: 66°C (machine 0, slot 1) 
| Current ASCII: "......." (length: 7)
| Current HEX:   0x0000000088b300
| Time elapsed: 7.8m | Time remaining: ~2.0d | Freq: 175.00MHz | Temp: 66°C (machine 0, slot 1) 
| Current ASCII: "......." (length: 7)
| Current HEX:   0x0000000000b400
| Time elapsed: 7.8m | Time remaining: ~2.0d | Freq: 175.00MHz | Temp: 66°C (machine 0, slot 1) 
| Current ASCII: "......." (length: 7)
| Current HEX:   0x0000000000b400
| Time elapsed: 7.8m | Time remaining: ~2.0d | Freq: 175.00MHz | Temp: 66°C (machine 0, slot 1) 
| Current ASCII: "....x.." (length: 7)

Could you point me how Cracklord gets the console messages?
My idea is to use the information for Time remaining in Time completion tab.

Thanks in advance!
Best regards,
Yanko

**Comment by ytronics** [comment]
Hello All,

Could you someone provide help about the using of following source fragment:
func (v *decryptTasker) Status() common.Job {
        log.WithField("task", v.job.UUID).Debug("Gathering task details")
	    v.mux.Lock()
	    defer v.mux.Unlock()

	    index := regAlgoOpts.FindAllStringIndex(v.stdout.String(), -1)
	    if len(index) >= 1 {
		// We found a status so start processing the last status in Stdout
		status := string(v.stdout.Bytes()[index[len(index)-1][0]:])
		log.WithField("Status Index", status).Debug("Status **********************")

		//Time to gather the progress
		progMatch := regProgress.FindStringSubmatch(status)
		log.WithField("progMatch", progMatch).Debug("Matching progress info")

		if len(progMatch) == 4 {
			prog, err := strconv.ParseFloat(progMatch[3], 64)
			log.WithField("Progres", prog).Debug("Progress **********************")
			if err == nil {
				v.job.Progress = prog
				log.WithField("progress", v.job.Progress).Debug("Job progress updated.")
			} else {
				log.WithField("error", err.Error()).Error("There was a problem converting progress to a number.")
			}
		}
   

	    etcMatch := regTimeRemaining.FindStringSubmatch(status)
		if len(etcMatch) == 2 {
			v.job.ETC = etcMatch[1]
		}
My problem is that I am trying to capture remaining time value from a terminal output:
| Time elapsed: 7.8m | Time remaining: ~2.0d | Freq: 175.00MHz | Temp: 66°C

I apply a regex for this row: progMatch := regProgress.FindStringSubmatch(status)
But it doesn't get anything from the row above. 

Could you explain me how regProgress.FindStringSubmatch works for hashcat tool?

Thanks in advance!

Best regards,

**Comment by jmmcatee** [comment]
Would it be possible to attack the files you are using for building your plugin. I'd like to see how you are copying the stdout into the buffer and where you are defining your regular expressions.

**Comment by ytronics** [comment]
Hello, 

I fixed the issue with the terminal output and I already can match the necessary information in my terminal. 
However I have issues with assignment of time value to ETC job.
Take a look on the problem:   

timing := regTimeEstimate.FindStringSubmatch(status)
// The timing string seems as:  ~2s . That meas approximately 2 seconds
       if len(timing) == 3 {
		v.job.ETC = timing[1] // Estimated time of completion
	} else {
		log.WithField("timing", timing).Debug("Did not match time estimate")
	}
When I run this piece of code I get the error:_ Recovered from Panic in Resource.TaskStatus: runtime error: index out of range _

I think that ETC uses only ciphers and these additional symbols cause the error.

Would you suggest me some approach for converting this string with the necessary information only?

Best regards,

**Comment by ytronics** [comment]
Hello All, 

I fixed the problem in my previous post. I have new issue with converting my hex result in int:
ERRO[0082] There was a problem converting progress to a number.  error=strconv.ParseInt: parsing "0xffffffffffffff": invalid syntax

 if len(ResultFind) >= 2 {
		      prog, err := strconv.ParseInt(ResultFind[1], 20, 128)
		     if err == nil {
			    v.job.CrackedHashes = prog
			    log.WithField("Result found", v.job.CrackedHashes).Debug("Decrypt job progress updated.")
		     } else {
			   log.WithField("error", err.Error()).Error("There was a problem converting progress to a number.")
		     }
	       } else {
		      log.WithField("hostsdone", ResultFind).Debug("Did not match Result.")
	       }

What can cause this problem?

Thanks in advance!

Best regards,

**Comment by jmmcatee** [comment]
I think your strconv.ParseInt is wrong. If you read the Go documentation for this your second number should be the base of the parsed value (if it is hex then this should be 16) and the second should be your bit size, which should be 64 from the hex value in your comment. Try again with strconv.ParseInt(ResultFind[1], 16, 64)
