### ISSUE TITLE
Not showing tools

### ISSUE THREAD

**Issue by toonswyzen** [jmmcatee/cracklord#108]
I have installed cracklord from the package that you have provided, but i cant seem to get it quite working. I have uncommented the nmap tool but it doesnt show up in the dropdown.

Here's the log from resourced.log:
[resourced.txt](https://github.com/jmmcatee/cracklord/files/182596/resourced.txt)

Perhaps i forgot to do something, it isn't quite clear to me what i should do to show them in the dropdown menu..

**Comment by jmmcatee** [comment]
Have you added the resource to the Queue server in the web interface?

**Comment by toonswyzen** [comment]
Thanks, that was indeed the mistake!

**Comment by jmmcatee** [comment]
No problem! Feel free to add any more issue or features you would like to see.
