### ISSUE TITLE
allow file upload for hashes

### ISSUE THREAD

**Issue by cyk1k** [jmmcatee/cracklord#110]
On the /jobs/new/details page, the current option is to paste hashes into the text box in order to process for cracking. However, this does not scale very well when attempting to crack large sets of hashes. It would be nice to have the ability to select a file to upload that contains hashes to crack.

**Comment by jmmcatee** [comment]
We definitely agree and have run into this ourselves. We are planning to make a few API changes to fix the display issue that come with this, but also make it easier to upload large hash files. We need a generic way to upload files for both this and WPA(2) and likely others such as the KeePass and TrueCrypt options. We have a rough idea how to do it, but have been working on a few performance and reliability things first. Planning on getting to this soon though. When we have a prototype, I'll reach out and have you test if that is alright.

**Comment by cyk1k** [comment]
Count me in for testing

**Comment by Koovu** [comment]
If you need others for testing, I'd also be interested. Very keen on the file upload and WPA(2) support!

**Comment by jmmcatee** [comment]
So the latest release should support this under the hashcat 3.10 plugin. You can now upload files, but we have had limited testing of the way this works.
