### ISSUE TITLE
Command's arguments and OS interpretation 

### ISSUE THREAD

**Issue by ytronics** [jmmcatee/cracklord#115]
Hello,
I am writing in your forum about a strange problem with command's arguments in my tool. 
Take a look on my issue:
The fragment from my source is:
// Process the arguments for the command and add them together
    args = append(args,config.BinPath)                                          // run se_forana
    args = append(args,"-f", filename)                                             // target file name  
    args = append(args,"-v", verboseSet)                                        // Verbosity
    **args = append(args,"--parameters","'")**                                      // Set parameters
    args = append(args,"--mode","dict")                                         // Dictionary mode
    args = append(args,"--machine", machineSet)                                 // Machine number
    args = append(args,"--dict-file", dictPath)                                 // Dictionary set 
    args = append(args,"--outfile", filepath.Join(f.wd, "forensic-pass.batch")) // Output file
    **args = append(args,"'")**

The running command seems correct as I expect:
Running command:                              argument=[............ -f filename4 -v 2 --parameters ' --mode dict --machine 0 --dict-file /mnt/dicts/FullListPass.txt --outfile /home/...../......./36ab48ab-da9c-44a0-b595-9729de8050bb/forensic-pass.batch ']

The problem is that the single quotes in my command. Linux OS does not recognize single quotes in the command generated by Cracklord. While there is no problem when I execute this command in Linux terminal. 

Would it be possible to suggest me a workaround or a tip to fix the issue with single quotes in my command?

Thanks in advance!

Best regards,

**Comment by jmmcatee** [comment]
So I'm just guessing here but I believe the way go's Cmd works is you need
to append the values in a key value type setup. I would create the entire
--parameter value and add it together instead of in pieces. I've seen weird
things before with this as the Cmd structure does not work exactly like a
shell input. Does that make any sense?

**Comment by ytronics** [comment]
Hello,

I tried to run the arguments in my command together, but there is not success. See the command:
 args = append(args,"-f", filename, "-v", verboseSet, "--parameters", "'--mode dict", "--machine", machineSet, "--dict-file", dictPath, "--outfile", filepath.Join(f.wd, "forensic-pass.batch'"))

The last part of the command is not recognized. However the part: '--mode dict", "--machine", machineSet, "--dict-file", dictPath, "--outfile", filepath.Join(f.wd, "forensic-pass.batch' - must be run together. 
Would it be possible to suggest me any approach for running this command?
I think that GO lang must provide such approach. 

Best regards,

**Comment by ytronics** [comment]
Hello,

It seems that, my machine accept the last part of the command as one part. However, cracklord generates this command on separate parts. Therefore the last part is not recognizable. I tried to make the last part of the command and then to concatenate with the first one. However there is no success. 

Would it be possible to suggest me an approach for generating the command in right way:
args = append(args,"-f", filename, "-v", verboseSet, "--parameters", "'--mode dict", "--machine", machineSet, "--dict-file", dictPath, "--outfile", filepath.Join(f.wd, "forensic-pass.batch'"))

Best regards,

**Comment by ytronics** [comment]
Hello All,

I have small progress with my problem. However, what may be the reason for  not recognizing of following string, generated as cli from cracklord. 
"'" + " " +"--mode" + " " + "dict" + " " + "--machine" + " " + machineSet + " " + "--dict-file" + " " + dictPath + " " + "--outfile" + " " + filepath.Join(f.wd, "forensic-pass.batch")+ " " + "'"
  
Do you have any ideas about my problem?
 Ongoing forensic task status                  status=running stderr=Warning: Unexpected argument: 

Best regards,

**Comment by jmmcatee** [comment]
I have not had time to take a look at your issue, but I can tell you how I
would troubleshoot it so maybe you can fix it in the short term. I would
build a small go program that you use to execute your tool under Go's Cmd
structure. This will be much easier to identify the edge cases with Cmd
than as part of the bigger Cracklord application. If I get some time I will
take a look at this, but that will likely not be this week.

**Comment by jmmcatee** [comment]
Any luck building a small tool to replicate this issue? Without the tool you are using I cannot test or troubleshoot this for you.

**Comment by ytronics** [comment]
Hello ,

Yes, I resolved my issue with my command interpretation. My issue was caused by single quotes in the last part of my command. I removed the single quotes and there is no problem with alignment between Cracklord and my Hardware.

Best regards.

**Comment by ytronics** [comment]
Hello ,

Yes, I resolved my issue with my command interpretation. My issue was caused by single quotes in the last part of my command. I removed the single quotes and there is no problem with alignment between Cracklord and my Hardware.

Best regards.
