### ISSUE TITLE
Resume file and start/stop/pause a job

### ISSUE THREAD

**Issue by ytronics** [jmmcatee/cracklord#116]
Hello,

I tested some features in Cracklord system and I found that I cannot resume a job. If I stop a given job, it cannot be resumed again. My tool generate a resume file and I want to use it. My idea is to use this file, when I resume a job. However, there is no such option in Cracklord.

Would it be possible to provide me an approach for resuming stopped jobs in a queue?

Thanks in advance!

Best regards,

**Comment by ytronics** [comment]
Hello, 

Could someone help me with resuming of stopped job in cracklord?

Please see my preliminary idea: 

func (q *Queue) ResumeResource(resUUID string) error {
	log.WithField("resource", resUUID).Debug("Attempting to resume resource.")

	q.Lock()
	defer q.Unlock()

		// Get the output results
	if file, err := os.Open(filepath.Join(v.wd, ".resume")); err == nil {
		log.Debug("resume file")
		linescanner := bufio.NewScanner(file)
		var linetmp [][]string
		for linescanner.Scan() {
			var kvp []string
			i := strings.Index(linescanner.Text(), "--algorithm", )
			kvp = append(kvp, linescanner.Text()[i+1:])
			kvp = append(kvp, linescanner.Text()[:i])

			linetmp = append(linetmp, kvp)
			log.Debug("Resume key searching with command:", linetmp)
		}
		
		if len(linetmp) > 0 {
			v.job.OutputData = linetmp
		}
	}

	v.cmd = *exec.Command("se_decrypt", "--resume")

	// Check for UUID existance
   //	if _, ok := q.pool[resUUID]; !ok {
	//	return errors.New("Resource with UUID provided does not exist!")
	//}

	//if q.pool[resUUID].Status != common.STATUS_PAUSED {
	//	return errors.New("Resource is not paused!")
	//}

	// Pool exists so unpause it
	res, _ := q.pool[resUUID]
	res.Status = common.STATUS_RUNNING
	q.pool[resUUID] = res

	// The keeper will take it from here
	return nil
}

I added the modification above in queue.go file. I check for .resume file in my work directory, then open the file and execute the command which use this file. 

Would it be possible to provide me any advises about my idea?

Best regards,
Yanko

**Comment by jmmcatee** [comment]
Ok so you are off here. That function is for resources not for jobs. Please
look at the hashcat plugin for an example of how to handle resuming a job.
You will not need to edit any of the cracklord code only your own tool
plugin. After reviewing the hashcat and John plugins for ideas, let us know
if you have questions.

**Comment by jmmcatee** [comment]
Another note to add to this. Each plugin has to implement the `Run() error` function, which needs to handle fresh starts and resumes on its own. The Hashcat and John plugins do this by checking the status of the Job type that is passed to the Tasker interface. If this status is Created, then you start fresh and if it is Paused then you Resume. All other statuses will be an error as you should only be starting or resuming a job from Created or Paused statuses. Does this make sense?

**Comment by ytronics** [comment]
Hello,

Thanks for your suggestion. I had resolved my issue with resuming a job. 

Best regards,
