### ISSUE TITLE
Save a job after closing cracklord system

### ISSUE THREAD

**Issue by ytronics** [jmmcatee/cracklord#118]
Hello,

I have a question: Can we save job parameters, when the connection between queue server and resource server is broken?
Can I open the job folder through the GUI interface? In this job folder is located the resume file and it is possible to start the job again.
I have observations, that when the connection between servers had been broken the running job is stopped and cannot be restarted. I restarted servers, but I cannot start the job again. Because I cannot see this old job in queue server.

Would it be possible to provide me a workaround about such problem with Cracklord?

Best regards,

**Comment by jmmcatee** [comment]
This is not a feature Cracklord supports at this time. I will add it to our
enhancement list, but designing this to work generically for any tool will
be challenging.
