### ISSUE TITLE
How to fix the resourceid with constant value

### ISSUE THREAD

**Issue by ytronics** [jmmcatee/cracklord#120]
Hello, 

I have a question about the using of a constant name for resourceid.
The resource id is changed every time, when a new session is set. Is there a possibility to stop generating of new resourceid and fix it to constant value? 

How I can fix a constant value for resourceid in cracklord source?

Thanks in advance!
Best regards,

**Comment by jmmcatee** [comment]
So the Resource ID is a UUID set by the queue when you connect a new one.
What is the use case you are looking for to have a constant one?

**Comment by ytronics** [comment]
Hello,

A simple description of my use case:
I want to fix resource id to constant value, because I have only one HW resource in my resource server. Therefore, I expect the resource server to have constant value for resource id when I connect to it.

I see that the resource id is changed every time, when I add my HW resource in the system. 
Can I fix resource id with constant value in the queue? 

Best regards,

**Comment by jmmcatee** [comment]
So there is not a way to change the Resource ID to be constant. The queue
has to have a unique ID each time. I'm still not sure why you would even
need to know the Resource ID. Are you calling the API from a script? If so
you can pull the Resource ID from the API programmatically as well.

**Comment by jmmcatee** [comment]
Closing, but let me know if you have more information or questions here.
