### ISSUE TITLE
Error building from source

### ISSUE THREAD

**Issue by klingsor83** [jmmcatee/cracklord#121]
Hi,

I would like to build cracklord from the sources following the instructions in the readme but when I execute the next command:
`go get github.com/jmmcatee/cracklord`

I get this error:
`can't load package: package github.com/jmmcatee/cracklord: no buildable Go source files in /root/work/src/github.com/jmmcatee/cracklord`

In the past, I tried to build the sources succesfully with the commands in the wiki but now I can't. Could you help me?

Thanks

**Comment by jmmcatee** [comment]
You need to build the two programs directly. Instead of building
github.com/jmmcatee/cracklord try building
github.com/jmmcatee/cracklord/cmd/queued and
github.com/jmmcatee/cracklord/cmd/resourced.

**Comment by klingsor83** [comment]
Thanks @jmmcatee  but if I execute:
`go get github.com/jmmcatee/cracklord/cmd/queued`
I get the next error:
`# github.com/jmmcatee/cracklord/cmd/queued
src/github.com/jmmcatee/cracklord/cmd/queued/req_functions.go:510: undefined: logrus.WithError`

**Comment by jmmcatee** [comment]
This commit (7d7352e5115e1d5ec4184f68b86e7a95adf1dc74) I just made to master fixed this issue.
