### ISSUE TITLE
How to delete a paused/stopped resource

### ISSUE THREAD

**Issue by ytronics** [jmmcatee/cracklord#123]
Hello,

Is there a option for deleting paused or stopped resource through the web interface?
I want to add new resource in the resource list but I want to delete the old one.

Best regards,

**Comment by jmmcatee** [comment]
Just committed (43590f9e5d9e100748f03fc6a85347cfb9e71bb5) a fix to this that should resolve the issue. You will need to rebuild from source to get the fix. We might push DEB package updates at some point. Working through a new plugin for hashcat is the priority right now.
