### ISSUE TITLE
`go get` does not work

### ISSUE THREAD

**Issue by ondj** [jmmcatee/cracklord#124]
Hi,

when I want to use `go get github.com/jmmcatee/cracklord` on current master, then this error is showed:

```
# cd /root/work/src/github.com/jmmcatee/cracklord; git submodule update --init --recursive
fatal: No url found for submodule path 'cracklord' in .gitmodules
package github.com/jmmcatee/cracklord: exit status 128
```

**Comment by jmmcatee** [comment]
This has been fixed in the latest release. This was a screw up in adding a sub-repo unintentionally.
