### ISSUE TITLE
Running Cracklord on NVIDIA DGX-1 super computer

### ISSUE THREAD

**Issue by ytronics** [jmmcatee/cracklord#125]
Hello All, 

Sorry for my question, it is not related with issues in Cracklord. 
I am researching the possibility for buying NVDIA DGX-1 super computer. I am interesting if someone from Cracklord's community is used NVIDIA DGX-1 super computer. 

Would it be possible to share with me more practical information about NVIDIA DGX-1 system or other GPU super computers?
Could you provide me an example of using DES crypto algorithm in Cracklord with super computer application?  

Thanks in advance!
Best regards,

**Comment by jmmcatee** [comment]
So I think you should focus on if Hashcat or John The Ripper would work on this cluster. Cracklord is only a Queue and job distribution system for those tools. It will run on any Linux/UNIX/Windows system if you can build Go binaries on it. My guess would be there are probably better job scheduling systems for super computing workloads. Please email me if you have other questions or any information to share about your usage on the super computer.
