### ISSUE TITLE
Support for hashcat version 3

### ISSUE THREAD

**Issue by nikben** [jmmcatee/cracklord#126]
Fusion of hashcat and oclHashcat (CPU + GPU) resulted in version 3.10 (see [https://hashcat.net/forum/thread-5559.html](https://hashcat.net/forum/thread-5559.html)).
Thus, oclhashcat no longer exists!
When will cracklord support the new version 3.10 of hashcat?

Thanks,
Nik

**Comment by jmmcatee** [comment]
If you run from source now it is supported with several upgrades. I have
some stability code to push. Let me do that tonight then you should be good
to build from source.

**Comment by nikben** [comment]
Thanks a lot!

**Comment by jmmcatee** [comment]
I just pushed more code to fix the 3.10 plugin. Should be working much better now. I will close this, but please reopen if you find any more issues.
