### ISSUE TITLE
hashcat process doesn't kill 

### ISSUE THREAD

**Issue by klingsor83** [jmmcatee/cracklord#127]
Hi,

I'm doing some test and I found a bug. If I have some jobs in current queue and I stop the running job pressing the corresponding button, this job isn't removed correctly. If I see the processes in the machine I see duplicated processes of hashcat corresponding to the removed job and the started new job.

Thanks

**Comment by klingsor83** [comment]
I think the problem was in https://github.com/jmmcatee/cracklord/blob/master/plugins/tools/hashcat/hashcat-tasker.go

In the conditional in Quit() method, you use "&&" and it should be "||".

Regards

**Comment by jmmcatee** [comment]
This is correct. I have this as an update that I have yet to commit. I
apologize for the delay. Hoping to get to it this weekend.

**Comment by jmmcatee** [comment]
This has now been fixed in the latest commit and DEB build. Let me know if this is fixed for you.
