### ISSUE TITLE
If hashcat finds the hash in the pot file, the hash is not displayed. 

### ISSUE THREAD

**Issue by lpaine** [jmmcatee/cracklord#129]
If I try to crack a hash I already cracked, hashcat finds it in the pot file, so the job kicks to complete but does not show the plaintext of the hash in the UI. This means I have to go hunt it down on the file system.

**Comment by jmmcatee** [comment]
I also have a fix for this. Just trying to find time to push the code.
Apologies. I'll reply to the ticket once I push. Hopefully this weekend.

**Comment by lpaine** [comment]
No worries, it's not blocking progress. Cracklord is awesome, I appreciate all the work you've done.

**Comment by jmmcatee** [comment]
@lpaine so this should now be fixed in the latest commit. If you built from source, just rebuild. If you are running the DEB install, then that should be updated to, but I have not done extensive testing of the new build process. Let me know if this is fixed for you.
