### ISSUE TITLE
Go get doesn't work

### ISSUE THREAD

**Issue by tautology0** [jmmcatee/cracklord#148]
You get the following message:

```
# cd /root/go/src/github.com/jmmcatee/cracklord; git submodule update --init --recursive
fatal: No url found for submodule path 'vendor/github.com/jmmcatee/goschemaform' in .gitmodules
package github.com/jmmcatee/cracklord: exit status 128
```

**Comment by azerty5896** [comment]
Hi,

My go get doesn't work neither, I have this message : 
`~/go/src/github.com/jmmcatee/cracklord/cmd/queued $ go get
go install runtime/internal/atomic: open /usr/local/go/pkg/linux_arm/runtime/internal/atomic.a: permission denied
`

@tautology0 Have you ever seen this message ?
Have you solve your problem ?

Julien

**Comment by DontFuckItUp** [comment]
Hi, 
i reproduced your issue on different ubuntu-systems and can confirm this issue. 
until now i haven't found a solution for that, only some things on stackexchange:
when 
 git ls-files --stage | grep 160000
160000 449e4218e507e3ea23226fc76256bc1b238fbac8 0       vendor/github.com/jmmcatee/goschemaform

after cloning your repro with git clone. 

seems to be the same issue like described here:
https://stackoverflow.com/questions/4185365/no-submodule-mapping-found-in-gitmodule-for-a-path-thats-not-a-submodule

i'm not very familar with git so i decided not to change that 

best

**Comment by jmmcatee** [comment]
I would not recommend 'go get' for pulling the code or installing. Either download the latest commit in ZIP format, clone the repo manually with git, or use the installer instruction if you are just looking to run Cracklord. Sorry about the confusion.

**Comment by tautology0** [comment]
Could you update readme.MD which instructs you to use go get?
