### ISSUE TITLE
installing via go get not possible

### ISSUE THREAD

**Issue by DontFuckItUp** [jmmcatee/cracklord#150]
Hello all,

there is an issue when using go to install your packages from github.
Environment:
Linux cracklord 3.13.0-129-generic #178-Ubuntu SMP Fri Aug 11 12:48:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty

root@cracklord:~# go version
go version go1.8.3 linux/amd64

go:
root@cracklord: go version
go version go1.8.3 linux/amd64
root@cracklord: go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/Projects/"
GORACE=""
GOROOT="/usr/local/go"

when running go on a fresh, clean, new system after apt update && apt upgrade -y
i run into this error after "go get github.com/jmmcatee/cracklord" command:

root@cracklord:~/Projects# go get github.com/jmmcatee/cracklord
cd /root/Projects/src/github.com/jmmcatee/cracklord; git submodule update --init --recursive
Keine Submodul-Zuordnung in .gitmodules für Pfad 'vendor/github.com/jmmcatee/goschemaform' gefunden
package github.com/jmmcatee/cracklord: exit status 1

"No submodule-link in.gitmodules for path vendor/github.com/jmmcatee/goschemaform or something similar. 

No Idea whats wrong.

**Comment by DontFuckItUp** [comment]
Hello, 
i tried the same with another minidistro from ubuntu:
Linux cracklord 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

go version go1.6.2 linux/amd64

same issue, same message . 
go get github.com/jmmcatee/cracklord
# cd /home/administrator/src/github.com/jmmcatee/cracklord; git submodule update --init --recursive
fatal: Keine Submodul-Zuordnung in .gitmodules für Pfad 'vendor/github.com/jmmcatee/goschemaform' gefunden
package github.com/jmmcatee/cracklord: exit status 128


thanks.

**Comment by jmmcatee** [comment]
go get will download the files, but you must follow the installation instructions the on GitHub website (http://jmmcatee.github.io/cracklord/) to install this solution.
