### ISSUE TITLE
no wpa2 key upload when installing from http://jmmcatee.github.io/cracklord/#install

### ISSUE THREAD

**Issue by ghost** [jmmcatee/cracklord#151]
Hello again,

i quick installed from http://jmmcatee.github.io/cracklord/#install using the binaries, but it seams there is no way to upload .hccapx, am i right? Of course i installed hashcat v3 and changed the hashcat3.conf.

**Comment by jmmcatee** [comment]
I believe this should work actually. Do you not see a check box that says "Use a file to upload hashes"? If you check that box, it will give you a file upload option in the Hashes form section.

**Comment by DontFuckItUp** [comment]
There is no Do you not see a check box that says "Use a file to upload hashes"? Field here when installing from http://jmmcatee.github.io/cracklord/#install  :(

**Comment by DontFuckItUp** [comment]
![image](https://user-images.githubusercontent.com/19187113/30962362-b84fdc26-a449-11e7-9b56-25c5654702fa.png)

installed from  http://jmmcatee.github.io/cracklord/#install

no checkbox shown.

**Comment by jmmcatee** [comment]
This should be fixed.
