### ISSUE TITLE
Brute Force Error "0.00%  ETA: ??:??:??"

### ISSUE THREAD

**Issue by applelian** [jmmcatee/cracklord#153]
Please help. I tried to brute force but always get errors

My command;
wpscan -u www.itsmysite.com -w /root/Desktop/password.txt --username admin -r --connect-timeout 20 --request-timeout 20 --threads 1

[+] Starting the password brute forcer
  [!] ERROR: No response from remote server. WAF/IPS? (Server returned nothing (no headers, no data))
  [!] ERROR: No response from remote server. WAF/IPS? (Server returned nothing (no headers, no data))
  [!] ERROR: No response from remote server. WAF/IPS? (Server returned nothing (no headers, no data))
  [!] ERROR: No response from remote server. WAF/IPS? (Server returned nothing (no headers, no data))
  [!] ERROR: No response from remote server. WAF/IPS? (Server returned nothing (no headers, no data))
  [!] ERROR: No response from remote server. WAF/IPS? (Server returned nothing (no headers, no data))
  [!] ERROR: No response from remote server. WAF/IPS? (Server returned nothing (no headers, no data))
  [!] ERROR: No response from remote server. WAF/IPS? (Server returned nothing (no headers, no data))
  [!] ERROR: No response from remote server. WAF/IPS? (Server returned nothing (no headers, no data))
  [!] ERROR: No response from remote server. WAF/IPS? (Server returned nothing (no headers, no data))
  [!] ERROR: No response from remote server. WAF/IPS? (Server returned nothing (no headers, no data))
  [!] ERROR: No response from remote server. WAF/IPS? (Server returned nothing (no headers, no data))
  [!] ERROR: No response from remote server. WAF/IPS? (Server returned nothing (no headers, no data))
  [!] ERROR: No response from remote server. WAF/IPS? (Server returned nothing (no headers, no data))
  [!] ERROR: No response from remote server. WAF/IPS? (Server returned nothing (no headers, no data))
  [!] ERROR: No response from remote server. WAF/IPS? (Server returned nothing (no headers, no data))
  [!] ERROR: No response from remote server. WAF/IPS? (Server returned nothing (no headers, no data))
  [!] ERROR: No response from remote server. WAF/IPS? (Server returned nothing (no headers, no data))
  [!] ERROR: No response from remote server. WAF/IPS? (Server returned nothing (no headers, no data))
  [!] ERROR: No response from remote server. WAF/IPS? (Server returned nothing (no headers, no data))
  [!] ERROR: No response from remote server. WAF/IPS? (Server returned nothing (no headers, no data))
  [!] ERROR: No response from remote server. WAF/IPS? (Server returned nothing (no headers, no data))
  [!] ERROR: No response from remote server. WAF/IPS? (Server returned nothing (no headers, no data))
  [!] ERROR: No response from remote server. WAF/IPS? (Server returned nothing (no headers, no data))
  [!] ERROR: No response from remote server. WAF/IPS? (Server returned nothing (no headers, no data))
  [!] ERROR: No response from remote server. WAF/IPS? (Server returned nothing (no headers, no data))
  [!] ERROR: No response from remote server. WAF/IPS? (Server returned nothing (no headers, no data))
  [!] ERROR: No response from remote server. WAF/IPS? (Server returned nothing (no headers, no data))
  [!] ERROR: No response from remote server. WAF/IPS? (Server returned nothing (no headers, no data))
  Brute Forcing 'admin' Time: 00:00:09 <                      > (35 / 14344393)  0.00%  ETA: ??:??:??
  +----+-------+------+----------+
  | ID | Login | Name | Password |
  +----+-------+------+----------+
  |    | admin |      |          |
  +----+-------+------+----------+

[!] The target seems to be down

Thank you very much in advance

**Comment by jmmcatee** [comment]
This does not appear to be about cracklord.
