### ISSUE TITLE
Export cuts off last digit of NTLM Hash

### ISSUE THREAD

**Issue by jbarcia** [jmmcatee/cracklord#56]
The output for NTLM Results, the last digit of the original NTLM hash is cut off. The resulting hash is only 31 chars, not the full 32

ex.
INPUT:
752dfe3cXXXXXXXXXX111b98668fb413
OUTPUT:
752dfe3cXXXXXXXXXX111b98668fb41

**Comment by jmmcatee** [comment]
This should be fixed in the next release
