### ISSUE TITLE
https://github.com/jmmcatee/cracklord/wiki/Creating-Resource-Certificates Non-Existant

### ISSUE THREAD

**Issue by raul5660** [jmmcatee/cracklord#69]
the url https://github.com/jmmcatee/cracklord/wiki/Creating-Resource-Certificates does not exist and redirects to https://github.com/jmmcatee/cracklord/wiki. When i click on 'Resource Certificates it redirects to same page

Not sure if i'm suppose to copy the certificates from the Queue server or create my own?

**Comment by emperorcow** [comment]
This is actually the only remaining open task for issue #15.  @jmmcatee should be creating that documentation today.

**Comment by raul5660** [comment]
my apologies didn't see that, thank you :)

**Comment by emperorcow** [comment]
No problem!  For the time being, you can probably find the commands you need in https://github.com/jmmcatee/cracklord/blob/master/build/queued/afterinstall.sh.  If you're working on setting up a resource server, you need to create a CSR and key, copy the CSR over to the queue server, sign it, and then copy the cert back to the resource.  

We should have a full 1.0 release here hopefully today, Michael and I are banging out a few remaining bugs, but if you notice anything we definitely would like to hear about it here.  Thanks!
