### ISSUE TITLE
John tool

### ISSUE THREAD

**Issue by raul5660** [jmmcatee/cracklord#74]
Not sure if i've made a mistake with the setup but when trying to use john all the job detail options have nothing populated in the dropdown menus.

# [Queue Server]
[General]
WebRoot=/var/cracklord/www

CACertFile=/etc/cracklord/ssl/cracklord_ca.pem
CAKeyFile=/etc/cracklord/ssl/cracklord_ca.key
CertFile=/etc/cracklord/ssl/queued.crt
KeyFile=/etc/cracklord/ssl/queued.key

BindIP=0.0.0.0
BindPort=443

LogFile=/var/log/cracklord/queued.log
LogLevel=Info

[Authentication] 
type=INI 
adminuser=admin 
adminpass=changeme 
standarduser=user 
standardpass=changeme 
readonlyuser=read 
readonlypass=changeme 

[ResourceManagers]
directconnect=true
#aws=/etc/cracklord/resourcemanagers/aws.conf

# [Resource Server(s)]
[General]
CACertFile=/etc/cracklord/ssl/cracklord_ca.pem
CertFile=/etc/cracklord/ssl/resourced.crt
KeyFile=/etc/cracklord/ssl/resourced.key

BindIP=0.0.0.0
BindPort=9443

LogFile=/var/log/cracklord/resourced.log
LogLevel=Info

[Plugins]
#hashcat=/etc/cracklord/plugins/hashcat.conf
nmap=/etc/cracklord/plugins/nmap.conf
johndict=/etc/cracklord/plugins/johndict.conf

**Comment by jmmcatee** [comment]
Can you post your john configuration and confirm you are using the john-jumbo community version?

**Comment by raul5660** [comment]
i doubt that i got the john-jumbo community version but will install that first

**Comment by raul5660** [comment]
Sorry for the late response but i finally got john-jumbo installed and all the hash types and dictionaries than you for your help

**Comment by nikben** [comment]
I'm sorry to bring this old thread up again.

I have john-jumbo installed on ubuntu 14.04.3 server and still have the same problem...

I followed this guide for john-jumbo:
[https://github.com/magnumripper/JohnTheRipper/blob/bleeding-jumbo/doc/INSTALL-UBUNTU](url)

Thanks in advance.
