### ISSUE TITLE
Jobs disappearing on completion

### ISSUE THREAD

**Issue by roo7break** [jmmcatee/cracklord#82]
After a job is complete, it disappears from the main page. The output is present within the "/var/cracklord/<GUID>/" location.

The error on Console is as follows - Seems angular is broken:

"Error: [$parse:syntax] http://errors.angularjs.org/1.4.1/$parse/syntax?p0='-'&p1=is%20an%20unexpected%20token&p2=18&p3=job.id%20%7C" "" "rderBy%20'-'&p4='-'
I/<@https://<ip_crackbox>/libs/angular.min.js:6:416
r.prototype.throwError@https://<ip_crackbox>/libs/angular.min.js:208:286
r.prototype.ast@https://<ip_crackbox>/libs/angular.min.js:201:1
qd.prototype.compile@https://<ip_crackbox>/libs/angular.min.js:210:130
hc.prototype.parse@https://<ip_crackbox>/libs/angular.min.js:236:161
gf/this.$get</<@https://<ip_crackbox>/libs/angular.min.js:118:288
Ce</<.compile@https://<ip_crackbox>/libs/angular.min.js:277:31
J@https://<ip_crackbox>/libs/angular.min.js:65:37
P@https://<ip_crackbox>/libs/angular.min.js:55:20
P@https://<ip_crackbox>/libs/angular.min.js:55:150
P@https://<ip_crackbox>/libs/angular.min.js:55:150
P@https://<ip_crackbox>/libs/angular.min.js:55:150
P@https://<ip_crackbox>/libs/angular.min.js:55:150
S@https://<ip_crackbox>/libs/angular.min.js:52:467
y/<.compile/<@https://<ip_crackbox>/libs/angular-ui-router.min.js:7:21904
Z@https://<ip_crackbox>/libs/angular.min.js:73:89
N@https://<ip_crackbox>/libs/angular.min.js:62:34
g@https://<ip_crackbox>/libs/angular.min.js:54:386
S/<@https://<ip_crackbox>/libs/angular.min.js:53:444
k@https://<ip_crackbox>/libs/angular-ui-router.min.js:7:21314
x/k.compile/</<@https://<ip_crackbox>/libs/angular-ui-router.min.js:7:21581
hf/this.$get</m.prototype.$broadcast@https://<ip_crackbox>/libs/angular.min.js:137:244
u/x.transitionTo/x.transition<@https://<ip_crackbox>/libs/angular-ui-router.min.js:7:17403
f/<@https://<ip_crackbox>/libs/angular.min.js:120:113
hf/this.$get</m.prototype.$eval@https://<ip_crackbox>/libs/angular.min.js:134:394
hf/this.$get</m.prototype.$digest@https://<ip_crackbox>/libs/angular.min.js:131:419
hf/this.$get</m.prototype.$apply@https://<ip_crackbox>/libs/angular.min.js:135:159
l@https://1<ip_crackbox>/libs/angular.min.js:87:150
N@https://<ip_crackbox>/libs/angular.min.js:91:187
Rf/</x.onload@https://<ip_crackbox>/libs/angular.min.js:92:220
"
Can you help?

**Comment by jmmcatee** [comment]
Are you using a state file? It would be configured in your Queue config file.

**Comment by roo7break** [comment]
Yes. How is the data stored if I dont use state file?

**Comment by roo7break** [comment]
I have fixed it (temporarily) by removing "orderby '-'" from one of the jobview html files.

However, for some reason the john's rules are not being captured. Hence the rule drop down is empty

**Comment by emperorcow** [comment]
Just a quick FYI, I've managed to replicate the issue and I'm looking into this one. Will try and get this fixed ASAP, sorry it's taken a couple days, work has been a bit crazy.

**Comment by emperorcow** [comment]
Took some time here over lunch and just got this fixed.  Commit incoming, I'm going to close but if it's still an issue please reopen and let us know.
