### ISSUE TITLE
Install script report errors

### ISSUE THREAD

**Issue by igorfuna** [jmmcatee/cracklord#86]
I'm trying to install Cracklord on Kali:

When I run

`curl -s https://packagecloud.io/install/repositories/emperorcow/cracklord/script.deb.sh | sudo bash`

I get the following error:

```
Detected operating system as Kali/moto.
Checking for curl...
Detected curl...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/emperorcow_cracklord.list...curl: (22) The requested URL returned error: 404
Unable to download repo config from: https://packagecloud.io/install/repositories/emperorcow/cracklord/config_file.list?os=Kali&dist=moto&source=script

Please contact support@packagecloud.io and report this.
```

Please advise.

**Comment by igorfuna** [comment]
I tried also to install in on Ubuntu / Precise.
The script works, however installation fails:

```
sudo apt-get update

......
Hit https://packagecloud.io precise Release.gpg
Hit https://packagecloud.io precise Release
Hit https://packagecloud.io precise/main Sources
Hit https://packagecloud.io precise/main amd64 Packages
Hit https://packagecloud.io precise/main i386 Packages
Ign https://packagecloud.io precise/main TranslationIndex
Get:1 https://packagecloud.io precise/main Translation-en_US [162 B]
Ign https://packagecloud.io precise/main Translation-en_US
Ign https://packagecloud.io precise/main Translation-en
```

```
sudo apt-get install cracklord-queued=1.0-beta-6-g16208b9

Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package cracklord-queued
```

**Comment by HCMUC** [comment]
What version of Ubuntu are u running?

**Comment by igorfuna** [comment]
Ubuntu 12.04.5 LTS

**Comment by HCMUC** [comment]
Did you try installing the deb packages?
https://packagecloud.io/emperorcow/cracklord

**Comment by igorfuna** [comment]
It seems this works.
Thanks for now.

**Comment by emperorcow** [comment]
Does anyone have any thoughts on a new package management solution we could use that would nicely support other distro's?  PackageCloud is nice because it's free and automatically supports Ubuntu and Debian, but there's certainly others we'd like to include as well. Let us know what thoughts you have

**Comment by vapor99** [comment]
I would recommend just using a Docker container.  I had a hell of a time trying to install this stuff on both Kali/Sana and Ubuntu/Vivid

**Comment by jmmcatee** [comment]
Docker would be challenging given the driver access to the GPU you need. It is doable, but might be tough to configure. What are other projects using to build DEBs and RPMs for various distros?

**Comment by elitest** [comment]
So is the initial problem that Kali hasn't been set up as a repo in packagecloud?  Would it work if you did a 
`package_cloud push emperorcow/cracklord/kali/sana cracklord-queued_1.0-beta-6-g16208b9_amd64.deb`?

I'm not sure what the current packaging process is but, there is also a fairly slick looking [debhelper](https://people.debian.org/~stapelberg/2015/07/27/dh-make-golang.html) script if the goal is to actually get it into Debian/Ubuntu repos.

Another option to improve the current process is to use a CI service like [Travis](https://travis-ci.org/) to do the building and [automatically upload to packagecloud](http://docs.travis-ci.com/user/deployment/packagecloud/).

I haven't looked at it in a while, but there is also the [OpenSuse Build Service](https://build.opensuse.org/).  I think it is supposed to build rpms and debs.

**Comment by jmmcatee** [comment]
We are going to fix packaging to support Ubuntu at many levels, Debian stable, and Kali rolling. This will be done as part of Milestone 1.1

**Comment by ringfanger** [comment]
How did you get this install script to work??  I've tried every repository in Ubuntu 12.04.5 LTS (and Ubuntu 16.04.1 LTS) with no luck.  

user@user-VirtualBox:~$ curl -s https://packagecloud.io/install/repositories/emperorcow/cracklord/script.deb.sh | sudo bash
Detected operating system as Ubuntu/precise.
Checking for curl...
Detected curl...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/emperorcow_cracklord.list...done.
Importing packagecloud gpg key... done.
Running apt-get update... done.

The repository is setup! You can now install packages.
user@user-VirtualBox:~$ sudo apt-get install cracklord-queued=1.0-beta-29-gc5e2878
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package cracklord-queued

**Comment by igorfuna** [comment]
I did it by installing the deb packages:
https://packagecloud.io/emperorcow/cracklord

**Comment by jmmcatee** [comment]
For now only Ubuntu is supported and unless someone has some expertise in package building it will likely stay that way. I will continue to try and update the build documentation so people can build it from source on various Linux/Unix/Windows systems.
