### ISSUE TITLE
[Feature] Upload Custom Dictionaries

### ISSUE THREAD

**Issue by jbarcia** [jmmcatee/cracklord#88]
Users should be able to add and remove custom dictionary files which contain client specific words such as location, sports teams, etc.
Users may/may not be provided write/delete access to the primary wordlists. You can also put a limit on the file size of the wordlist.

**Comment by jmmcatee** [comment]
There is some code in hashcat and john right now to let you a custom list to the front of a dictionary, but it is comments out and has not been tested. Would this be sufficent? You could have an empty dictionary choice then let people create a custom wordlist to add to it. What is a sane size limit here?

**Comment by jmmcatee** [comment]
You can now add custom values to the existing list of dictionaries in the 3.10 plugin.
