### ISSUE TITLE
WPA/WPA2 supported but none-functional

### ISSUE THREAD

**Issue by sleventyeleven** [jmmcatee/cracklord#89]
hashcat supports WPA/WPA2 cracking, however the file must be converted, into a binary format for cracking, making it impossible to upload binary blob into the text based hash input box. If WPA/WPA2 cracking is to be supported, a file uploaded option should be used to allow for the hccap file to be properly submitted.

**Comment by igorfuna** [comment]
Another vote for this.

**Comment by jugganuts420** [comment]
yes please

**Comment by kolet** [comment]
agree with that,
also john the ripper support wpa and wpa2

**Comment by jmmcatee** [comment]
So I have two notes for this. First the newest build that I will hopefully push to the packages today removes WPA/WPA2 from our list for oclHashcat. This is because it requires us to be able to upload files, which we have not done yet. The good news is we are going to do this for milestone 1.1. This will not only be helpful for WPA/WPA2 but also for large hash files and I believe stuff like the KeePass and TrueCrypt options.

**Comment by dr0v3r** [comment]
Ok so there is a possible workaround currently, that I threw into my local installation. Manually base64 encoding the .hccap file contents, submitting it via the UI and programmatically decoding that data prior to passing to hashcat works fine.

I won't issue a pull request seeing as it's clearly a hackaround and the upstream fixes would be more permanent, such as the use of a file upload function to take the hashes that way.

File to modify: hashcat-tasker.go and algorithms.go

Within algorithms.go, uncomment the WPA/WPA2 hashtype to re-enable it.

Within hashcat-tasker.go:

Added the required base64 includes.
```
import (
         "encoding/base64"
```

Added a function:

```
func decodeHccap(encoded string, err error) (string, error){
        decoded, _ := base64.StdEncoding.DecodeString(encoded)
        return string(decoded), err
}
```

There is this if statement, to identify the hashtype (around line 154):
```
    if !ok {
                log.WithFields(log.Fields{
                        "algoritm": htype,
                        "err":      ok,
                }).Error("Could not find the algorithm provided")
                return &hascatTasker{}, errors.New("Could not find the algorithm provided.")
        }
```

Immediatly after this, and before the os.Create(), I have added the below code:
```
    var decoded string
    if htype == "2500" {
                decoded, err = decodeHccap(h.job.Parameters["hashes"], err)
                h.job.Parameters["hashes"] = decoded
                }
```

Not pretty, but just a temporary solution.

**Comment by jmmcatee** [comment]
This should now work in the hashcat 3 plugin. You will need to build from
source to test.
