### ISSUE TITLE
PackageCloud package update?

### ISSUE THREAD

**Issue by sardonyxserendil** [jmmcatee/cracklord#90]
Hello,

I'm using your PackageCloud repo and I was just wondering how often will it be updated?  I'm suffering from bug #82 and would like to get it resolved.

Thank you!

**Comment by HCMUC** [comment]
You can simply fix it manually! just edit 2 lines in web interface code :/

**Comment by sardonyxserendil** [comment]
Thanks, I should have looked at the commit before posting.
