### ISSUE TITLE
Use increment mode for hashcat

### ISSUE THREAD

**Issue by HCMUC** [jmmcatee/cracklord#91]
The hashcat plugin cracks only the hashes with the configured password length but how often do you know the password length exactly?

If you want to find a collision for a 3 character password-hash and you configured 8 characters there will no collision be found (except of bad luck).

Hashcat supports the 'increment' mode which supports this!

btw the documentation...

**Comment by emperorcow** [comment]
I merged both of your pull requests, I think this fixes this issue, but I wanted to double check.  Thanks for taking the time to get this in, we really appreciate it!

**Comment by emperorcow** [comment]
Can you let us know if this is fully working with the new deb files?  If so, please close the issue, thanks!

**Comment by HCMUC** [comment]
elitest fixed a compiler error and pulled it. I guess the error caused that no new deb files were created :/. Sorry for that!

**Comment by HCMUC** [comment]
I compiled the fixed build from elitest and the increment mode works!

**Comment by jmmcatee** [comment]
We will be pushing a new release shortly that provides the incremental mode. I have changed how it works compared to elitest to fit our new form building library. I'll be pushing this build today so let me know if it works for you.
