### ISSUE TITLE
run hashcat as different user

### ISSUE THREAD

**Issue by jugganuts420** [jmmcatee/cracklord#94]
# Note that resourced will, if you used a package, run as cracklord-user
# Depending on the drivers, hashcat sometimes needs to run as a specific user

how do i tell cracklord to run oclhashcat as root instead of cracklord-user?

**Comment by jugganuts420** [comment]
or better put how do i make cracklord-resourced run as root?

**Comment by jugganuts420** [comment]
ok so i found a temporary fix

first stop the cracklord-resourced service

"service cracklord-resourced stop"

then start it from root account

"cracklord-resourced"

and leave the terminal window open (DONT CLOSE IT THAT WILL SHUT THE RESOURCED SERVER DOWN)

**Comment by emperorcow** [comment]
So if you edit /etc/init/cracklord-resourced.conf (link here for the version on github https://github.com/jmmcatee/cracklord/blob/master/build/resourced/cracklord-resourced.conf) you should see a line that says setuid.  If you change that to whatever user you want, it will run as that user.  Just be aware of the risk of running things as root.

**Comment by HCMUC** [comment]
Hashcat should work without any special permissions. Maybe you meant nmap? nmap -sS works only on root!

**Comment by jugganuts420** [comment]
thx works and no i mean oclhashcat due to drivers i need to run as root or sudo or hashcat will crash
