### ISSUE TITLE
Jobs disapper after completed/stopped

### ISSUE THREAD

**Issue by jugganuts420** [jmmcatee/cracklord#95]
after a job is completed/stopped the job completely disappears and i can not review my results

**Comment by dekanfrus** [comment]
Check this out: https://github.com/jmmcatee/cracklord/issues/82

If you used the repo to install cracklord, just grab the two files (jobsController.js, jobsView.html) that were changed and update them locally until they update the repo.  Alternatively, you could just grab the lines that were changed in the commit that fixed the issue (https://github.com/jmmcatee/cracklord/commit/bcec1348c9e37d81871b33e0eff5bfb6d1377034)

**Comment by emperorcow** [comment]
I'm going to go ahead and push a build so that this issue is taken care of for folks.  You should see the debs update in just a little bit.
