### ISSUE TITLE
[Hashcat] Blank NTLM Password

### ISSUE THREAD

**Issue by emperorcow** [jmmcatee/cracklord#99]
When you get back a blank NTLM hash 31d6cfe0d16ae931b73c59d7e0c089c0 the result comes back in the output field under job details as 1 instead of blank.

**Comment by jmmcatee** [comment]
This is a decision in Hashcat that 0 length hashes are not supported. We
would have to hard code a check for these in all the hashes not support at
0 length by Hashcat.
